Restore NPM_TOKEN variable mapping

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,6 +6,9 @@ stages:
   - post_deploy
   - pages
 
+variables:
+  NPM_TOKEN: $NPM_AUTH_TOKEN
+
 default:
   image: node:20
   before_script:
@@ -89,11 +92,12 @@ deploy_packages:
       }
     - |
       if [ "${CI_COMMIT_BRANCH}" = "main" ]; then
-        if [ -z "${NPM_TOKEN:-}" ]; then
-          echo "NPM_TOKEN is required to publish" >&2
+        npm_token="${NPM_TOKEN:-${NODE_AUTH_TOKEN:-}}"
+        if [ -z "${npm_token}" ]; then
+          echo "NPM_TOKEN or NODE_AUTH_TOKEN is required to publish" >&2
           exit 1
         fi
-        npm config set //registry.npmjs.org/:_authToken="${NPM_TOKEN}"
+        npm config set //registry.npmjs.org/:_authToken="${npm_token}"
         publish_package apps/packages/web-components
         publish_package apps/packages/react-components
       else
